name: Smoke Tests - PR - Robot Framework

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4


      - name: Instalar python 3.12.2
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-faker

      - name: Configurar Chrome e Chromedriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: "latest" # Versão mais recente do Chrome
          chromedriver-cache: true # Cache do Chromedriver para evitar downloads repetidos
                   
      - name: Run test
        run: robot TestePages/register_teste.robot

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-tests
          path: '/TestePages/Report'

      - name: Download Tests Results
        if: always()
        uses: actions/download-artifact@v1
        with:
          name: results

    

