name: Smoke Tests - PR - Robot Framework

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4


      - name: Instalar python 3.12.2
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-faker
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromedriver    

      

      - name: Run test
        run: robot TestePages/register_teste.robot

      - name: Gerar relatório
        if: always()
        run: robot --outputdir  Report

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-tests
          path: '**/TestePages/Report'

    

