name: Smoke Tests - PR - Robot Framework

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4


      - name: Instalar python 3.12.2
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-faker

      - name: Instalar o chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar o chromedriver
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional    
                   
      - name: Run test
        run: robot TestePages/register_teste.robot

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-tests
          path: '**/TestePages/Report'

    

